version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - unused
        path: server/configuration.go
      - linters:
          - bodyclose
          - scopelint
        path: _test\.go
      - linters:
          - revive
        text: unused-parameter
      - linters:
          - errcheck
        text: c.Abort
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/mattermost/mattermost-starter-template
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
