// Copyright (c) 2023-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

package streaming

import (
	"github.com/mattermost/mattermost/server/public/model"
)

const LLMRequesterUserID = "llm_requester_user_id"
const RespondingToProp = "responding_to"
const NoRegen = "no_regen"
const UnsafeLinksPostProp = "unsafe_links"

// ModifyPostForBot modifies a post to add bot-specific properties
func ModifyPostForBot(botid string, requesterUserID string, post *model.Post, respondingToPostID string) {
	post.UserId = botid
	post.Type = "custom_llmbot" // This must be the only place we add this type for security.
	post.AddProp(LLMRequesterUserID, requesterUserID)
	// This tags that the post has unsafe links since they could have been generated by a prompt injection.
	// This will prevent the server from making OpenGraph requests and markdown images being rendered.
	post.AddProp(UnsafeLinksPostProp, "true")

	// Add the ID of the post we're responding to
	if respondingToPostID != "" {
		post.AddProp(RespondingToProp, respondingToPostID)
	}
}
